/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type HealthStatusBot = {
  running: boolean;
  startedAt: string | null;
};

export interface HealthStatus {
  status: string;
  bot: HealthStatusBot;
}

