/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { HealthStatusBot } from './healthStatusBot';

export interface HealthStatus {
  status: string;
  bot: HealthStatusBot;
}
